---
peers:
  - csrv2.lab
  - csrv3.lab
  - csrv4.lab

bgp_global:
    as_number: '65536'
    bgp:
      log_neighbor_changes: true
      router_id:
        address: 10.10.2.13
    neighbors:
    - log_neighbor_changes:
        set: true
      neighbor_address: 10.10.2.35
      remote_as: '65539'
    - log_neighbor_changes:
        set: true
      neighbor_address: 10.10.2.63
      remote_as: '65537'
    - log_neighbor_changes:
        set: true
      neighbor_address: 10.10.2.151
      remote_as: '65538'

bgp_address_family:
    address_family:
    - afi: ipv4
      neighbor:
      - activate: true
        address: 10.10.2.35
      - activate: true
        address: 10.10.2.63
      - activate: true
        address: 10.10.2.151
      network:
      - address: 192.0.2.0
      - address: 192.0.3.0
      - address: 192.0.4.0
    as_number: '65536'
